name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Process-Hider.sln /p:Configuration=Release /p:Platform=x64

    - name: Sign Executable
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE_BASE64 }}'
        password: '${{ secrets.CERTIFICATE_PASSWORD }}'
        folder: 'x64/Release'
        recursive: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          x64/Release/CopiIot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
